apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gunicorn-killer-3000-binding
subjects:
  - kind: ServiceAccount
    name: gunicorn-killer-3000
    namespace: default
roleRef:
  kind: ClusterRole
  name: gunicorn-killer-3000
  apiGroup: rbac.authorization.k8s.io
